// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.

use sql_server_2025_master_msdb_sandbox_combined_catalog::core::config_manager::load_config;
use sql_server_2025_master_msdb_sandbox_combined_catalog::core::sanitizer::sanitize;

pub fn run() -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;
    let sanitized = sanitize(&serde_json::to_value(&config)?);
    println!("{}", serde_json::to_string_pretty(&sanitized)?);
    Ok(())
}
