// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.

use sqlserver_mcp_catalog::core::config_manager::load_config;
use sqlserver_mcp_catalog::data::store::cached_store_connection;
use sqlserver_mcp_catalog::tools::get_tool::get_operation;

pub async fn run(operation_id: &str) -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;
    let conn = cached_store_connection(&config.api_version)?
        .lock()
        .unwrap();
    let result = get_operation(&conn, operation_id)?;
    println!("{}", serde_json::to_string_pretty(&result)?);
    Ok(())
}
