// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.
//
// `sqlserver-mcp`'s own entry-point wiring — not declared in `lib.rs`,
// since no other `[[bin]]` target needs it (see `lib.rs`'s own doc comment).

pub mod call;
pub mod config;
pub mod get;
pub mod search;
pub mod setup;
pub mod setup_wizard;
pub mod test_connection;
pub mod version;
pub mod versions;
