// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.

use sql_server_2025_master_msdb_sandbox_combined_catalog::core::config_manager::load_config;
use sql_server_2025_master_msdb_sandbox_combined_catalog::data::store::cached_store_connection;
use sql_server_2025_master_msdb_sandbox_combined_catalog::tools::search_tool::search_operations;

pub async fn run(query: &str, limit: usize) -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;
    let conn = cached_store_connection(&config.api_version)?
        .lock()
        .unwrap();
    let results = search_operations(&conn, query, limit)?;
    println!("{}", serde_json::to_string_pretty(&results)?);
    Ok(())
}
