// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.

use sqlserver_mcp_catalog::core::config_manager::load_config;
use sqlserver_mcp_catalog::data::store::cached_store_connection;
use sqlserver_mcp_catalog::tools::search_tool::search_operations;

pub async fn run(
    query: &str,
    limit: usize,
    profile_warmups: usize,
    profile_iterations: usize,
) -> anyhow::Result<()> {
    if profile_iterations == 0 {
        anyhow::bail!("--profile-iterations must be at least 1");
    }

    let config = load_config(serde_json::Map::new())?;
    let conn = cached_store_connection(&config.api_version)?
        .lock()
        .unwrap();

    for _ in 0..profile_warmups {
        search_operations(&conn, query, limit)?;
    }

    let started = std::time::Instant::now();
    let mut results = serde_json::Value::Null;
    for _ in 0..profile_iterations {
        results = search_operations(&conn, query, limit)?;
    }

    if profile_warmups > 0 || profile_iterations > 1 {
        let elapsed = started.elapsed();
        eprintln!(
            "profile workload: {profile_warmups} warmup(s), {profile_iterations} measured iteration(s), {:.3} ms/iteration",
            elapsed.as_secs_f64() * 1_000.0 / profile_iterations as f64
        );
    }

    println!("{}", serde_json::to_string_pretty(&results)?);
    Ok(())
}
