// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.

pub fn run() -> anyhow::Result<()> {
    println!("{}", env!("CARGO_PKG_VERSION"));
    Ok(())
}
