#!/usr/bin/env python3
"""Merge <version>/{master,msdb,sandbox}.yaml into <version>/combined.yaml.

Each of the three per-database specs uses the same synthetic mapping
convention (see ../README.md) and, critically, reuses identical paths and
operationIds across databases -- e.g. every database has an
INFORMATION_SCHEMA.COLUMNS view, so `INFORMATION_SCHEMA_COLUMNS` and
`/INFORMATION_SCHEMA/COLUMNS` appear in all three files. OpenAPI's `paths`
map allows only one operation per method+path in a single document, so
merging requires prefixing both `path` and `operationId` with the database
name to make them disjoint. That prefix doubles as the only place the
generated MCP server can recover which database an operation targets,
since mcpify does not carry OpenAPI vendor extensions (`x-sql-database`)
through into its generated store.
"""
import argparse
import pathlib
import sys

import yaml

DATABASES = ("master", "msdb", "sandbox")


def load(openapi_dir: pathlib.Path, db: str) -> dict:
    with open(openapi_dir / f"{db}.yaml") as f:
        return yaml.safe_load(f)


def prefix_paths(spec: dict, db: str) -> dict:
    prefixed = {}
    for path, path_item in spec["paths"].items():
        new_path = f"/{db}{path}"
        new_item = dict(path_item)
        for method, op in new_item.items():
            if not isinstance(op, dict) or "operationId" not in op:
                continue
            new_op = dict(op)
            new_op["operationId"] = f"{db}_{op['operationId']}"
            new_item[method] = new_op
        prefixed[new_path] = new_item
    return prefixed


def merge_schemas(specs: dict) -> dict:
    merged: dict = {}
    conflicts = []
    for db, spec in specs.items():
        for name, schema in spec.get("components", {}).get("schemas", {}).items():
            if name in merged and merged[name] != schema:
                conflicts.append((name, db))
                continue
            merged[name] = schema
    if conflicts:
        details = ", ".join(f"{name} (from {db})" for name, db in conflicts)
        raise ValueError(
            f"components.schemas name collision with differing content: {details}. "
            "The merge script assumes identically-named schemas are byte-identical "
            "across master/msdb/sandbox -- update merge_schemas() to suffix and "
            "repoint refs for these before proceeding."
        )
    return merged


def merge_version(openapi_dir: pathlib.Path, version: str) -> dict:
    specs = {db: load(openapi_dir, db) for db in DATABASES}

    paths: dict = {}
    for db in DATABASES:
        paths.update(prefix_paths(specs[db], db))

    schemas = merge_schemas(specs)

    base = specs["master"]
    combined = {
        "openapi": base["openapi"],
        "info": {
            "title": f"SQL Server {version} - master/msdb/sandbox combined catalog",
            "version": version,
            "description": (
                f"Synthetic OpenAPI representation of curated system stored procedures, "
                f"functions, and catalog views across the 'master', 'msdb', and 'sandbox' "
                f"databases on SQL Server {version}, merged from the three per-database "
                f"specs generated by tools/generate_openapi.py. Every path is prefixed with "
                f"its source database (/<master|msdb|sandbox>/<schema>/<name>) and every "
                f"operationId likewise (<db>_<schema>_<name>), since the three source specs "
                f"reuse identical paths/operationIds across databases (e.g. every database "
                f"has its own INFORMATION_SCHEMA.COLUMNS). See the per-database files' own "
                f"description and ../README.md for the underlying mapping convention."
            ),
        },
        "paths": paths,
        "components": {
            "schemas": schemas,
            "securitySchemes": base["components"]["securitySchemes"],
        },
        "security": base["security"],
    }
    return combined


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", choices=["2017", "2019", "2022", "2025"])
    args = parser.parse_args()

    openapi_dir = pathlib.Path(__file__).resolve().parent.parent / "openapi" / args.version
    combined = merge_version(openapi_dir, args.version)

    out_path = openapi_dir / "combined.yaml"
    with open(out_path, "w") as f:
        yaml.safe_dump(combined, f, sort_keys=False, width=100)

    print(f"wrote {out_path} ({len(combined['paths'])} paths, "
          f"{len(combined['components']['schemas'])} schemas)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
