#!/usr/bin/env bash
# SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.
# Heap profiling via dhat-rs, kept separate from Samply so allocator
# instrumentation cannot distort CPU samples.
set -euo pipefail
cd "$(dirname "$0")/.."

export SQLSERVER_URL="${SQLSERVER_URL:-localhost}"
export SQLSERVER_AUTH_METHOD="${SQLSERVER_AUTH_METHOD:-sql_server}"

profile_query="${PROFILE_QUERY:-test query}"
profile_warmups="${PROFILE_HEAP_WARMUPS:-1}"
profile_iterations="${PROFILE_HEAP_ITERATIONS:-5}"

cargo run --release --features profiling --bin sqlserver-mcp -- search "$profile_query" \
  --profile-warmups "$profile_warmups" \
  --profile-iterations "$profile_iterations"

echo
echo "Heap profile written to:"
echo "  dhat-heap.json (view at https://nnethercote.github.io/dh_view/dh_view.html)"
