#!/usr/bin/env bash
# SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.
# CPU profiling via samply (works on macOS/Linux without sudo/dtrace).
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v samply >/dev/null 2>&1; then
  echo "error: samply not found. Install it with:" >&2
  echo "  cargo install samply" >&2
  echo "  samply setup   # macOS only: codesigns samply for process attach" >&2
  exit 1
fi

mkdir -p profile

# `search` only reads the embedded semantic store, but the shared config
# loader still requires these two fields. Safe local defaults keep profiling
# self-contained while preserving any explicit operator configuration.
export SQLSERVER_URL="${SQLSERVER_URL:-localhost}"
export SQLSERVER_AUTH_METHOD="${SQLSERVER_AUTH_METHOD:-sql_server}"

profile_query="${PROFILE_QUERY:-test query}"
profile_warmups="${PROFILE_WARMUPS:-3}"
profile_iterations="${PROFILE_ITERATIONS:-250}"

cargo build --release

samply record --save-only --unstable-presymbolicate -o profile/profile.json.gz -- \
  ./target/release/sqlserver-mcp search "$profile_query" \
    --profile-warmups "$profile_warmups" \
    --profile-iterations "$profile_iterations" \
  2> >(tee profile/workload.txt >&2)

python3 scripts/samply_to_text.py \
  profile/profile.json.gz \
  profile/folded-stacks.txt \
  profile/cpu-top.txt

{
  echo "# Generated server bottleneck report"
  echo
  echo "Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "## Workload"
  echo
  echo "- Query: \`$profile_query\`"
  echo "- Warmups: $profile_warmups"
  echo "- Measured iterations: $profile_iterations"
  echo "- Build: uninstrumented release (DHAT disabled)"
  if grep -q '^profile workload:' profile/workload.txt; then
    echo "- Measurement: $(grep -m1 '^profile workload:' profile/workload.txt | sed 's/^profile workload: //')"
  fi
  echo
  if [ -f target/coverage/lcov.info ]; then
    echo "## Largest coverage gaps"
    echo
    echo '```'
    awk '
      /^SF:/ { file=substr($0,4); hit=0; total=0 }
      /^DA:/ { total++; split($0,a,","); if (a[2]+0 > 0) hit++ }
      /^end_of_record/ { if (total > 0) { pct = 100*hit/total; printf "%6d missed  %6.1f%% covered  %s  (%d/%d lines)\n", total-hit, pct, file, hit, total } }
    ' target/coverage/lcov.info | sort -nr | head -20
    echo '```'
    echo
  fi
  echo "## Hottest functions (CPU, self-time sample count)"
  echo
  echo '```'
  tail -n +2 profile/cpu-top.txt | head -20
  echo '```'
} > profile/bottleneck-report.md

echo
echo "Profile written to:"
echo "  profile/profile.json.gz    (interactive — samply load profile/profile.json.gz)"
echo "  profile/cpu-top.txt        (LLM/tool-ingestable)"
echo "  profile/workload.txt       (measured warm-workload latency)"
echo "  profile/bottleneck-report.md (combined coverage + hot-path summary; run scripts/coverage.sh first for the coverage section)"
echo
echo "For a separate DHAT heap profile: bash scripts/profile-heap.sh"
