// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.
//
// Library crate shared by every `[[bin]]` target in this project
// (`sqlserver-mcp`, `sqlserver-mcp-populate-embeddings`, `sqlserver-mcp-healthcheck`)
// — each `[[bin]]` is its own separate crate, so anything they need in
// common (config, auth, the data layer, tool logic) has to live here rather
// than as plain `mod` declarations in `main.rs`, which only `main.rs`
// itself could see. `cli` is deliberately not declared here: it's
// `sqlserver-mcp`'s own entry-point wiring, used by no other binary.

pub mod auth;
pub mod core;
pub mod data;
pub mod http;
pub mod services;
pub mod tools;
pub mod validation;
