// SQL Server 2025 - master/msdb/sandbox combined catalog MCP server — generated by mcpify. Do not hand-edit.

use thiserror::Error;

#[derive(Debug, Error)]
pub enum AuthError {
    #[error("missing required credential field(s): {0}")]
    MissingCredentials(String),

    #[error("access token expired and could not be refreshed")]
    TokenExpired,

    #[error(
        "no valid credentials for auth method '{0}'; run `sql-server-2025-master-msdb-sandbox-combined-catalog setup`"
    )]
    NoActiveCredentials(String),
}
